.TH OBJICC 1 "v\ 1" "Mon, May 18, 2009" "DARWIN\ \-\ MAC\ OS\ X"
.SH NAME
.B objicc
\- the objic compiler
.SH SYNOPSIS
objic [-d] [-h] [-v]
.br
.SH OPTIONS
.TP
.B -d
Enables debug mode
.TP
.B -h
Prints a help message
.TP
.B -v
Prints the version of the compiler
.SH DESCRIPTION
The compiler for the objic language
.br
.SH VERSION
This documentation describes
.B objicc
version 1
.SH "SEE ALSO"
Objserver orun
.br
.I http://objic.ribalba.de site
.SH AUTHOR
.br
.B Hoffmann Geerd-Dietger
.br
.I \<didi@ribalba.de\>
