.TH OBJSERVER 1 "v\ 1" "Mon, May 18, 2009" "LINUX"
.SH NAME
.B ObjServer
\- Initializes the main server
.SH SYNOPSIS
ObjServer [-h] [-v] [-d]
.br
.SH OPTIONS
.TP
.B --h
Prints out a help message and exits
.TP
.B --d
Enables debug output also called verbose mode
.TP
.B --v
Prints out the version number
.SH DESCRIPTION
Starts the main server loop waiting for connections and executes the objects
.br
.SH VERSION
This documentation describes
.B ObjServer
version 1
.SH "SEE ALSO"
orun objicc
.br
.I http://objic.ribalba.de site
.SH AUTHOR
.br
.B Hoffmann Geerd-Dietger
.br
.I \<didi@ribalba.de\>
