.TH ORUN 1 "v\ 1" "Mon, May 18, 2009" "GNU/LINUX"
.SH NAME
.B orun
\- objic runner
.SH SYNOPSIS
orun [-d] [-h] [-v] class params server
.br
.SH OPTIONS
.TP
.B --d
Debug Mode
.TP
.B --h
Print help and exit
.TP
.B --v
Echo version and exit
.SH DESCRIPTION
This program initializes the class on the server and executes the main mehtod
.br
.SH EXAMPLES
Example 1:  ./orun fib 10
.br
This will run the fib class and pass in the parameter 10
.P
.SH VERSION
This documentation describes
.B orun
version 1
.SH "SEE ALSO"
globalConf.py objicc ObjServer
.br
.I objic.ribalba.de site
.SH AUTHOR
.br
.B Hoffmann Geerd-Dietger
.br
.I \<didi@ribalba.de\>
